version: '3'


services:

  
  nats-server:
    image: nats:latest


  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: southamerica-west1-docker.pkg.dev/tienda-microservice/image-registry/client-gateway
    ports:
      - "${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}"
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222


  auth-ms:
    container_name: auth-ms
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: southamerica-west1-docker.pkg.dev/tienda-microservice/image-registry/auth-ms
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  products-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: southamerica-west1-docker.pkg.dev/tienda-microservice/image-registry/products-ms-prod
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  # # orders-ms:
  orders-ms:
    build: 
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: southamerica-west1-docker.pkg.dev/tienda-microservice/image-registry/orders-ms
    environment:
      - PORT=3002
      - DATABASE_URL=${ORDERS_DATABASE_URL}
      - NATS_SERVERS=nats://nats-server:4222



  payments-ms:
    container_name: payments-ms
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: southamerica-west1-docker.pkg.dev/tienda-microservice/image-registry/payments-ms
    ports:
      - "${PAYMENTS_PORT_PORT}:3003"
    environment:
      - PORT=${PAYMENTS_PORT_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINTSECRET=${STRIPE_ENDPOINTSECRET}



    
